ListaLeitura/Models/ErrorViewModel.cs
namespace ListaLeitura.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ListaLeitura/Models/ListaLeituraModel.cs
using ListaLeitura.Enums;
using System.ComponentModel.DataAnnotations;


namespace ListaLeitura.Models
{
    public class ListaLeituraModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Preencha o nome")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Preencha o autor")]
        public string Autor { get; set; }

        [Required(ErrorMessage = "Preencha o status")]
        public StatusEnum Status { get; set; }

        [Required(ErrorMessage = "Preencha o ano da leitura")]
        public int AnoLeitura { get; set; }
    }
}

ListaLeitura/Controllers/ListaLeituraController.cs
using ListaLeitura.Data;
using ListaLeitura.Models;
using Microsoft.AspNetCore.Mvc;

namespace ListaLeitura.Controllers
{
    public class ListaLeituraController : Controller
    {
        private readonly AppDbContext _context;

        public ListaLeituraController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            IEnumerable<ListaLeituraModel> listaLeitura = _context.ListaLeituras;

            return View(listaLeitura);
        }

        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(ListaLeituraModel listaLeitura)
        {
            if(ModelState.IsValid)
            {
                _context.ListaLeituras.Add(listaLeitura);
                _context.SaveChanges();

                TempData["MensagemSucesso"] = "Cadastro realizado com sucesso";

                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        public IActionResult Editar(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }

            ListaLeituraModel listaLeitura = _context.ListaLeituras.FirstOrDefault(x => x.Id == id);

            if(listaLeitura == null)
            {
                return NotFound();
            }

            return View(listaLeitura);
        }

        [HttpPost]
        public IActionResult Editar(ListaLeituraModel listaLeituraModificada)
        {
            if(ModelState.IsValid)
            {
                _context.ListaLeituras.Update(listaLeituraModificada);
                _context.SaveChanges();

                TempData["MensagemSucesso"] = "Editado com sucesso";

                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        public IActionResult Excluir(int? id) 
        { 
            if(id == null || id == 0)
            {
                return NotFound();
            }

            ListaLeituraModel listaLeitura = _context.ListaLeituras.FirstOrDefault(x => x.Id == id);

            return View(listaLeitura);
        }

        [HttpPost]
        public IActionResult Excluir(ListaLeituraModel listaLeitura)
        {
            if(ModelState.IsValid)
            {
                _context.ListaLeituras.Remove(listaLeitura);
                _context.SaveChanges();

                TempData["MensagemSucesso"] = "Excluído com sucesso";

                return RedirectToAction("Index");
            }

            return View();
        }
    }
}

ListaLeitura/Views/ListaLeitura/Cadastrar.cshtml
@model ListaLeituraModel

@{
    ViewData["title"] = "Nova Leitura";
}

<div class="container bg-dark p-5 rounded-3">
    <div class="mb-5 text-center text-light">
        <h1>Cadastrar Nova Leitura</h1>
    </div>

    <form method="post" asp-controller="ListaLeitura" asp-action="Cadastrar">
        <div class="mb-3">
            <label for="Nome" class="form-label text-light">Nome do Livro</label>
            <input type="text" class="form-control" asp-for="Nome" id="Nome" placeholder="Nome do Livro" />
            <span class="text-danger" asp-validation-for="Nome"></span>
        </div>
        <div class="mb-3">
            <label for="Autor" class="form-label text-light">Autor</label>
            <input type="text" class="form-control" asp-for="Autor" id="Autor" placeholder="Autor do Livro" />
            <span class="text-danger" asp-validation-for="Autor"></span>
        </div>
        <div class="mb-3">
            <label for="Status" class="form-label text-light">Status</label>
            <select class="form-select" asp-for="Status" aria-label="Selecione o status">
                <option selected>Selecione o Status</option>
                <option value="0">Concluído</option>
                <option value="1">Lendo</option>
                <option value="2">Pausado</option>
                <option value="3">Abandonado</option>
            </select>
        </div>
        <div class="mb-3">
            <label for="AnoLeitura" class="form-label text-light">Ano da Leitura</label>
            <input type="text" class="form-control" asp-for="AnoLeitura" id="AnoLeitura" placeholder="Ano da Leitura" />
            <span class="text-danger" asp-validation-for="AnoLeitura"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Salvar</button>
            <a class="btn btn-primary w-50" asp-controller="ListaLeitura" asp-action="Index">Voltar</a>
        </div>
    </form>
</div>

ListaLeitura/Views/ListaLeitura/Editar.cshtml
@model ListaLeituraModel

@{
    ViewData["title"] = "Editar Leitura";
}

<div class="container bg-dark p-5 rounded-3">

    <div class="mb-5 text-center text-light">
        <h1>Editar Leitura</h1>
    </div>

    <form method="post" asp-controller="ListaLeitura" asp-action="Editar">

        <input type="hidden" asp-for="Id" />
        <div class="mb-3">
            <label for="Nome" class="form-label text-light">Nome do Livro</label>
            <input type="text" class="form-control" asp-for="Nome" id="Nome" placeholder="Nome do Livro" />
            <span class="text-danger" asp-validation-for="Nome"></span>
        </div>
        <div class="mb-3">
            <label for="Autor" class="form-label text-light">Autor</label>
            <input type="text" class="form-control" asp-for="Autor" id="Autor" placeholder="Autor do Livro" />
            <span class="text-danger" asp-validation-for="Autor"></span>
        </div>
        <div class="mb-3">
            <label for="Status" class="form-label text-light">Status</label>
            <select class="form-select" asp-for="Status" aria-label="Selecione o status">
                <option selected>Selecione o Status</option>
                <option value="0">Concluído</option>
                <option value="1">Lendo</option>
                <option value="2">Pausado</option>
                <option value="3">Abandonado</option>
            </select>
        </div>
        <div class="mb-3">
            <label for="AnoLeitura" class="form-label text-light">Ano da Leitura</label>
            <input type="text" class="form-control" asp-for="AnoLeitura" id="AnoLeitura" placeholder="Ano da Leitura" />
            <span class="text-danger" asp-validation-for="AnoLeitura"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Salvar</button>
            <a class="btn btn-primary w-50" asp-controller="ListaLeitura" asp-action="Index">Voltar</a>
        </div>
    </form>
</div>

ListaLeitura/Views/ListaLeitura/Excluir.cshtml
@model ListaLeituraModel

@{
    ViewData["title"] = "Excluir Leitura";
}

<div class="container bg-dark p-5 rounded-3">

    <div class="mb-5 text-center text-light">
        <h1>Excluir Leitura</h1>
    </div>

    <form method="post" asp-controller="ListaLeitura" asp-action="Excluir">
        <input type="hidden" asp-for="Id" />
        <div class="mb-3">
            <label for="Nome" class="form-label text-light">Nome do Livro</label>
            <input type="text" class="form-control" asp-for="Nome" id="Nome" placeholder="Nome do Livro" readonly/>
            <span class="text-danger" asp-validation-for="Nome"></span>
        </div>
        <div class="mb-3">
            <label for="Autor" class="form-label text-light">Autor</label>
            <input type="text" class="form-control" asp-for="Autor" id="Autor" placeholder="Autor do Livro" readonly/>
            <span class="text-danger" asp-validation-for="Autor"></span>
        </div>
        <div class="mb-3">
            <label for="Status" class="form-label text-light">Status</label>
            <input type="text" class="form-control" asp-for="Status" id="Status" placeholder="Autor do Livro" readonly/>
            <span class="text-danger" asp-validation-for="Status"></span>
        </div>
        <div class="mb-3">
            <label for="AnoLeitura" class="form-label text-light">Ano da Leitura</label>
            <input type="text" class="form-control" asp-for="AnoLeitura" id="AnoLeitura" placeholder="Ano da Leitura" readonly/>
            <span class="text-danger" asp-validation-for="AnoLeitura"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-danger w-50">Excluir</button>
            <a class="btn btn-primary w-50" asp-controller="ListaLeitura" asp-action="Index">Voltar</a>
        </div>
    </form>

</div>

ListaLeitura/Views/ListaLeitura/Index.cshtml
@model IEnumerable<ListaLeituraModel>

<div class="container">
    
    <div class="d-flex justify-content-between align-items-center mb-5">
        <h1>Lista de Leituras</h1>
        <a class="btn btn-success mx-2" asp-controller="ListaLeitura" asp-action="Cadastrar"><i class="bi bi-file-earmark-plus mx-2"></i>Cadastrar</a>
    </div>

    @if(TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success text-black" role="row">
            @TempData["MensagemSucesso"]
        </div>
    }

    <table id="ListaLeitura" class="table table-light table-hover mt-5">
        <thead>
            <tr>
                <th scope="col">Nome do Livro</th>
                <th scope="col">Autor</th>
                <th scope="col">Status</th>
                <th scope="col">Ano da Leitura</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if(Model != null)
            {
                @foreach(var lista in Model)
                {
                    <tr>
                        <th scope="row">@lista.Nome</th>
                        <td>@lista.Autor</td>
                        <td>@lista.Status</td>
                        <td>@lista.AnoLeitura</td>
                        <td>
                            <a class="btn btn-warning mx-2" asp-controller="ListaLeitura" asp-action="Editar" asp-route-id="@lista.Id"><i class="bi bi-pencil-square mx-2"></i>Editar</a>
                            <a class="btn btn-danger mx-2" asp-controller="ListaLeitura" asp-action="Excluir" asp-route-id="@lista.Id"><i class="bi bi-trash3-fill mx-2"></i>Excluir</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

ListaLeitura/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lista de Leitura</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Sketchy.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ListaLeitura.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.datatables.net/v/dt/dt-2.1.5/datatables.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="ListaLeitura" asp-action="Index">Lista de Leituras</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ListaLeitura" asp-action="Index"><i class="bi bi-house-fill mx-2"></i>Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

@*    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ListaLeitura
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-2.1.5/datatables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>